set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sinsible'

set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

unbind r
bind r source-file ~/.tmux.conf

unbind ^A
bind ^A select-pane -t :.+

setw -g mode-keys vi

bind-key R respawn-window

set -g default-shell /usr/bin/fish

set -g extended-keys on

